---
fixtures:
  repositories:
    concat: https://github.com/simp/puppetlabs-concat
    elasticsearch:
      repo: https://github.com/simp/puppet-elasticsearch
      ref: 5.5.0
    grafana:
      repo: https://github.com/simp/puppet-grafana
      ref: v4.1.1
    iptables: https://github.com/simp/pupmod-simp-iptables
    java:
      repo: https://github.com/simp/puppetlabs-java
      ref: 2.4.0
    pki: https://github.com/simp/pupmod-simp-pki
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib

    # Fixtures for the acceptance test
    datacat:
      repo: https://github.com/simp/puppet-datacat
      ref: simp6.0.0-0.6.2
    pam: https://github.com/simp/pupmod-simp-pam
    rsync: https://github.com/simp/pupmod-simp-rsync
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simp: https://github.com/simp/pupmod-simp-simp
    simp_apache: https://github.com/simp/pupmod-simp-apache
    simp_elasticsearch: https://github.com/simp/pupmod-simp-simp_elasticsearch
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master

  symlinks:
    simp_grafana: "#{source_dir}"
